#!/bin/bash
intern=eDP1
extern=DP2-2

if xrandr | grep "$extern connected"; then
    xrandr --output "$extern" --auto
    xrandr --output "$intern" --off
else
    xrandr --output "$extern" --off
    xrandr --output "$intern" --auto
fi
